import type {
  Farmer,
  InsectCapture,
  MarketplaceItem,
  CreditTransaction,
} from "@/modules/shared/types";

// ─── Mock Farmers ─────────────────────────────────────────────────────────────

export const MOCK_FARMERS: Farmer[] = [
  {
    id: "farmer-001",
    name: "Ahmed Khan",
    farmName: "Green Valley Orchards",
    location: "Veridian Valley Reserve, Punjab",
    coordinates: { lat: 31.5497, lng: 74.3436 },
    fieldAreaHectares: 24.5,
    farmingMethod: "organic",
    waterSource: "rainFed",
    carbonCredits: 1284,
    totalCaptures: 347,
    joinedAt: "2024-03-12",
    weather: { temp: 24, humidity: 62, condition: "Partly Cloudy" },
  },
  {
    id: "farmer-002",
    name: "Sara Malik",
    farmName: "Sunrise Fields",
    location: "Amber Wetlands, Sindh",
    coordinates: { lat: 25.3960, lng: 68.3578 },
    fieldAreaHectares: 16.0,
    farmingMethod: "transitioning",
    waterSource: "irrigated",
    carbonCredits: 640,
    totalCaptures: 189,
    joinedAt: "2024-06-01",
    weather: { temp: 29, humidity: 55, condition: "Sunny" },
  },
  {
    id: "farmer-003",
    name: "Bilal Raza",
    farmName: "Highland Fern Estate",
    location: "Highland Ferns, KPK",
    coordinates: { lat: 34.0151, lng: 71.5249 },
    fieldAreaHectares: 31.2,
    farmingMethod: "commercial",
    waterSource: "mixed",
    carbonCredits: 120,
    totalCaptures: 54,
    joinedAt: "2025-01-18",
    weather: { temp: 18, humidity: 78, condition: "Overcast" },
  },
  {
    id: "farmer-004",
    name: "Nadia Hussain",
    farmName: "River Bend Farms",
    location: "Northern Corridor, Gilgit",
    coordinates: { lat: 35.9208, lng: 74.3087 },
    fieldAreaHectares: 9.8,
    farmingMethod: "organic",
    waterSource: "rainFed",
    carbonCredits: 890,
    totalCaptures: 212,
    joinedAt: "2024-09-05",
    weather: { temp: 14, humidity: 70, condition: "Fog" },
  },
];

// ─── Mock Insect Captures ─────────────────────────────────────────────────────

export const MOCK_CAPTURES: InsectCapture[] = [
  {
    id: "cap-001",
    kind: "butterfly",
    commonName: "Monarch Traveler",
    scientificName: "Danaus plexippus",
    timestamp: "2024-10-12T14:32:01Z",
    lat: 31.552,
    lng: 74.351,
    trajectory: "NNE @ 12.4 km/h",
    aiConfidence: 94.8,
    notes: "Observed near mossy roots, shimmer like oil on water.",
  },
  {
    id: "cap-002",
    kind: "beetle",
    commonName: "Emerald Leaf Beetle",
    scientificName: "Chrysolina herbacea",
    timestamp: "2024-10-13T09:15:44Z",
    lat: 31.548,
    lng: 74.340,
    trajectory: "SE @ 2.1 km/h",
    aiConfidence: 91.2,
  },
  {
    id: "cap-003",
    kind: "bee",
    commonName: "Apis mellifera",
    scientificName: "Apis mellifera",
    timestamp: "2024-10-13T11:05:00Z",
    lat: 31.558,
    lng: 74.362,
    trajectory: "W @ 8.7 km/h",
    aiConfidence: 97.1,
  },
  {
    id: "cap-004",
    kind: "ladybug",
    commonName: "Seven-spot Ladybug",
    scientificName: "Coccinella septempunctata",
    timestamp: "2024-10-14T20:33:22Z",
    lat: 31.541,
    lng: 74.329,
    trajectory: "N @ 1.2 km/h",
    aiConfidence: 88.5,
  },
  {
    id: "cap-005",
    kind: "butterfly",
    commonName: "Blue Morpho",
    scientificName: "Morpho menelaus",
    timestamp: "2024-10-15T13:20:10Z",
    lat: 31.562,
    lng: 74.375,
    trajectory: "SW @ 15.3 km/h",
    aiConfidence: 96.3,
    notes: "Rare sighting in this region.",
  },
  {
    id: "cap-006",
    kind: "beetle",
    commonName: "Monarch-Crested Beetle",
    scientificName: "Dynastes speciosus",
    timestamp: "2024-10-16T08:45:00Z",
    lat: 31.539,
    lng: 74.334,
    trajectory: "E @ 3.4 km/h",
    aiConfidence: 89.9,
    notes: "Rare specimen flagged by Node 42-B.",
  },
];

// ─── Marketplace Items ────────────────────────────────────────────────────────

export const MARKETPLACE_ITEMS: MarketplaceItem[] = [
  {
    id: "item-001",
    name: "Bio-Regen Fertilizer",
    description: "Enhanced microbial liquid formula for deep root sequestration.",
    creditCost: 450,
    category: "fertilizer",
    iconName: "Sprout",
  },
  {
    id: "item-002",
    name: "Heritage Seed Pack",
    description: "Ancient variety grains resistant to drought and high salinity.",
    creditCost: 120,
    category: "seeds",
    iconName: "Flower2",
  },
  {
    id: "item-003",
    name: "IoT Soil Sensors",
    description: "Real-time nitrogen and moisture tracking for carbon yield.",
    creditCost: 980,
    category: "sensor",
    iconName: "Cpu",
  },
  {
    id: "item-004",
    name: "Precision Irrigation Kit",
    description: "Reduces water waste by 40% using smart zone targeting.",
    creditCost: 750,
    category: "equipment",
    iconName: "Droplets",
  },
  {
    id: "item-005",
    name: "Compost Accelerator",
    description: "Enzymatic blend to fast-track organic matter decomposition.",
    creditCost: 200,
    category: "fertilizer",
    iconName: "Recycle",
  },
  {
    id: "item-006",
    name: "Canopy Net System",
    description: "Pollinators protection mesh for crop boundary areas.",
    creditCost: 310,
    category: "equipment",
    iconName: "Shield",
  },
];

// ─── Credit Transactions ──────────────────────────────────────────────────────

export const MOCK_TRANSACTIONS: CreditTransaction[] = [
  {
    id: "tx-001",
    farmerId: "farmer-001",
    amount: 150,
    type: "earned",
    description: "Butterfly capture batch #34 — 12 specimens",
    timestamp: "2024-10-12T14:35:00Z",
  },
  {
    id: "tx-002",
    farmerId: "farmer-001",
    amount: 450,
    type: "redeemed",
    description: "Redeemed: Bio-Regen Fertilizer",
    timestamp: "2024-10-10T09:00:00Z",
  },
  {
    id: "tx-003",
    farmerId: "farmer-001",
    amount: 200,
    type: "released",
    description: "Government credit release — Q3 organic certification",
    timestamp: "2024-10-01T00:00:00Z",
  },
  {
    id: "tx-004",
    farmerId: "farmer-001",
    amount: 90,
    type: "earned",
    description: "Beetle capture batch #28 — 6 specimens",
    timestamp: "2024-09-28T16:20:00Z",
  },
];

// ─── Insect kinds metadata ────────────────────────────────────────────────────

export const INSECT_KINDS = [
  {
    kind: "butterfly" as const,
    label: "Butterflies",
    scientificName: "Danaus plexippus",
    emoji: "🦋",
    color: "bg-green-100 text-green-800",
    description: "Lepidoptera — migratory pollinators",
    captureCount: 156,
  },
  {
    kind: "beetle" as const,
    label: "Beetles",
    scientificName: "Chrysolina herbacea",
    emoji: "🪲",
    color: "bg-amber-100 text-amber-800",
    description: "Coleoptera — soil decomposers",
    captureCount: 89,
  },
  {
    kind: "bee" as const,
    label: "Bees",
    scientificName: "Apis mellifera",
    emoji: "🐝",
    color: "bg-yellow-100 text-yellow-800",
    description: "Hymenoptera — essential pollinators",
    captureCount: 74,
  },
  {
    kind: "ladybug" as const,
    label: "Ladybugs",
    scientificName: "Coccinella septempunctata",
    emoji: "🐞",
    color: "bg-blue-100 text-blue-800",
    description: "Coccinellidae — beneficial aphid predators",
    captureCount: 28,
  },
];
